resources:
  repositories:
    - repository: azure-sdk-build-tools
      type: git
      name: internal/azure-sdk-build-tools
      ref: refs/tags/azure-sdk-build-tools_20211215.1

parameters:
- name: CopyFromPartnerDrops
  displayName: 'Copy From AzureSdkPartnerDrops'
  type: boolean
  default: true
- name: SignPackages
  displayName: 'Sign Packages'
  type: boolean
  default: false
- name: PublishSymbols
  displayName: 'Publish Symbols'
  type: boolean
  default: false
- name: PublishToNuget
  displayName: 'Publish to Nuget'
  type: boolean
  default: false
- name: PublishToBlobFeed
  displayName: 'Publish to Blob Feed'
  type: boolean
  default: false
- name: PublishToDevOpsFeed
  displayName: 'Publish to DevOps Feed'
  type: boolean
  default: false
- name: CopySignedFilesToBlob
  displayName: 'Copy Signed Files to Blob'
  type: boolean
  default: false
- name: NugetVersion
  displayName: 'Nuget Version'
  type: string
  default: ''

jobs:
  - job: NupkgRelease
    pool:
      name: azsdk-pool-mms-win-2019-general
      vmImage: MMS2019
  steps: 
    - template: /eng/pipelines/templates/steps/net-release-to-any.yml
      parameters:
        CopyFromPartnerDrops: ${{ parameters.BuildToolsRepoPath }}
        SignPackages: ${{ parameters.SignPackages }}
        PublishSymbols: ${{ parameters.PublishSymbols }}
        PublishToNuget: ${{ parameters.PublishToNuget }}
        PublishToBlobFeed: ${{ parameters.PublishToBlobFeed }}
        PublishToDevOpsFeed: ${{ parameters.PublishToDevOpsFeed }}
        CopySignedFilesToBlob: ${{ parameters.CopySignedFilesToBlob }}
        NugetVersion: ${{ parameters.NugetVersion }}